services:

  backend1:

    build:
      context: ../Backend

    container_name: syncdocs-backend1

    environment:

      PORT: 8080

      NODE_ENV: production

      CLIENT_URL: ${CLIENT_URL}

      MONGODB_URI: ${MONGODB_URI}

      JWT_SECRET: ${JWT_SECRET}

      REDIS_URL: ${REDIS_URL}

      USE_REDIS: "true"

      DISABLE_RATE_LIMIT: "true"

    ports:

      - "8080:8080"

  backend2:

    build:
      context: ../Backend

    container_name: syncdocs-backend2

    environment:

      PORT: 8080

      NODE_ENV: production

      CLIENT_URL: ${CLIENT_URL}

      MONGODB_URI: ${MONGODB_URI}

      JWT_SECRET: ${JWT_SECRET}

      REDIS_URL: ${REDIS_URL}

      USE_REDIS: "true"

      DISABLE_RATE_LIMIT: "true"

    ports:

      - "8081:8080"